//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbaseModel", "FK_menu_menu", "menu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pro.Models.menu), "menu1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(pro.Models.menu), true)]
[assembly: EdmRelationshipAttribute("dbaseModel", "FK_area_city", "city", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(pro.Models.city), "area", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(pro.Models.area), true)]

#endregion

namespace pro.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbaseEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbaseEntities1 object using the connection string found in the 'dbaseEntities1' section of the application configuration file.
        /// </summary>
        public dbaseEntities1() : base("name=dbaseEntities1", "dbaseEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbaseEntities1 object.
        /// </summary>
        public dbaseEntities1(string connectionString) : base(connectionString, "dbaseEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbaseEntities1 object.
        /// </summary>
        public dbaseEntities1(EntityConnection connection) : base(connection, "dbaseEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<contactinfo> contactinfoes
        {
            get
            {
                if ((_contactinfoes == null))
                {
                    _contactinfoes = base.CreateObjectSet<contactinfo>("contactinfoes");
                }
                return _contactinfoes;
            }
        }
        private ObjectSet<contactinfo> _contactinfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<menu> menus
        {
            get
            {
                if ((_menus == null))
                {
                    _menus = base.CreateObjectSet<menu>("menus");
                }
                return _menus;
            }
        }
        private ObjectSet<menu> _menus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<furniture> furnitures
        {
            get
            {
                if ((_furnitures == null))
                {
                    _furnitures = base.CreateObjectSet<furniture>("furnitures");
                }
                return _furnitures;
            }
        }
        private ObjectSet<furniture> _furnitures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<house> houses
        {
            get
            {
                if ((_houses == null))
                {
                    _houses = base.CreateObjectSet<house>("houses");
                }
                return _houses;
            }
        }
        private ObjectSet<house> _houses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<job> jobs
        {
            get
            {
                if ((_jobs == null))
                {
                    _jobs = base.CreateObjectSet<job>("jobs");
                }
                return _jobs;
            }
        }
        private ObjectSet<job> _jobs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<land> lands
        {
            get
            {
                if ((_lands == null))
                {
                    _lands = base.CreateObjectSet<land>("lands");
                }
                return _lands;
            }
        }
        private ObjectSet<land> _lands;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mobile> mobiles
        {
            get
            {
                if ((_mobiles == null))
                {
                    _mobiles = base.CreateObjectSet<mobile>("mobiles");
                }
                return _mobiles;
            }
        }
        private ObjectSet<mobile> _mobiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<camera> cameras
        {
            get
            {
                if ((_cameras == null))
                {
                    _cameras = base.CreateObjectSet<camera>("cameras");
                }
                return _cameras;
            }
        }
        private ObjectSet<camera> _cameras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<area> areas
        {
            get
            {
                if ((_areas == null))
                {
                    _areas = base.CreateObjectSet<area>("areas");
                }
                return _areas;
            }
        }
        private ObjectSet<area> _areas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<car> cars
        {
            get
            {
                if ((_cars == null))
                {
                    _cars = base.CreateObjectSet<car>("cars");
                }
                return _cars;
            }
        }
        private ObjectSet<car> _cars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<city> cities
        {
            get
            {
                if ((_cities == null))
                {
                    _cities = base.CreateObjectSet<city>("cities");
                }
                return _cities;
            }
        }
        private ObjectSet<city> _cities;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the contactinfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocontactinfoes(contactinfo contactinfo)
        {
            base.AddObject("contactinfoes", contactinfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the menus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomenus(menu menu)
        {
            base.AddObject("menus", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the furnitures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofurnitures(furniture furniture)
        {
            base.AddObject("furnitures", furniture);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the houses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohouses(house house)
        {
            base.AddObject("houses", house);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the jobs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTojobs(job job)
        {
            base.AddObject("jobs", job);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lands EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolands(land land)
        {
            base.AddObject("lands", land);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mobiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomobiles(mobile mobile)
        {
            base.AddObject("mobiles", mobile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cameras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocameras(camera camera)
        {
            base.AddObject("cameras", camera);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the areas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToareas(area area)
        {
            base.AddObject("areas", area);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocars(car car)
        {
            base.AddObject("cars", car);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocities(city city)
        {
            base.AddObject("cities", city);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="area")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class area : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new area object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="areaname">Initial value of the areaname property.</param>
        /// <param name="cid">Initial value of the cid property.</param>
        public static area Createarea(global::System.String id, global::System.String areaname, global::System.Int32 cid)
        {
            area area = new area();
            area.id = id;
            area.areaname = areaname;
            area.cid = cid;
            return area;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String areaname
        {
            get
            {
                return _areaname;
            }
            set
            {
                OnareanameChanging(value);
                ReportPropertyChanging("areaname");
                _areaname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("areaname");
                OnareanameChanged();
            }
        }
        private global::System.String _areaname;
        partial void OnareanameChanging(global::System.String value);
        partial void OnareanameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cid
        {
            get
            {
                return _cid;
            }
            set
            {
                OncidChanging(value);
                ReportPropertyChanging("cid");
                _cid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cid");
                OncidChanged();
            }
        }
        private global::System.Int32 _cid;
        partial void OncidChanging(global::System.Int32 value);
        partial void OncidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbaseModel", "FK_area_city", "city")]
        public city city
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("dbaseModel.FK_area_city", "city").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("dbaseModel.FK_area_city", "city").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<city> cityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<city>("dbaseModel.FK_area_city", "city");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<city>("dbaseModel.FK_area_city", "city", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="camera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class camera : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new camera object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="brandname">Initial value of the brandname property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="posttime">Initial value of the posttime property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="location">Initial value of the location property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        public static camera Createcamera(global::System.Int32 id, global::System.String brandname, global::System.Double price, global::System.DateTime posttime, global::System.String status, global::System.String location, global::System.String phone)
        {
            camera camera = new camera();
            camera.id = id;
            camera.brandname = brandname;
            camera.price = price;
            camera.posttime = posttime;
            camera.status = status;
            camera.location = location;
            camera.phone = phone;
            return camera;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String brandname
        {
            get
            {
                return _brandname;
            }
            set
            {
                OnbrandnameChanging(value);
                ReportPropertyChanging("brandname");
                _brandname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("brandname");
                OnbrandnameChanged();
            }
        }
        private global::System.String _brandname;
        partial void OnbrandnameChanging(global::System.String value);
        partial void OnbrandnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Double _price;
        partial void OnpriceChanging(global::System.Double value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String image
        {
            get
            {
                return _image;
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.String _image;
        partial void OnimageChanging(global::System.String value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime posttime
        {
            get
            {
                return _posttime;
            }
            set
            {
                OnposttimeChanging(value);
                ReportPropertyChanging("posttime");
                _posttime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("posttime");
                OnposttimeChanged();
            }
        }
        private global::System.DateTime _posttime;
        partial void OnposttimeChanging(global::System.DateTime value);
        partial void OnposttimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="car")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class car : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new car object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="brand">Initial value of the brand property.</param>
        /// <param name="image">Initial value of the image property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="poston">Initial value of the poston property.</param>
        /// <param name="area">Initial value of the area property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="email">Initial value of the email property.</param>
        public static car Createcar(global::System.Int32 id, global::System.String brand, global::System.String image, global::System.String price, global::System.String phone, global::System.String status, global::System.DateTime poston, global::System.String area, global::System.String password, global::System.String email)
        {
            car car = new car();
            car.id = id;
            car.brand = brand;
            car.image = image;
            car.price = price;
            car.phone = phone;
            car.status = status;
            car.poston = poston;
            car.area = area;
            car.password = password;
            car.email = email;
            return car;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String brand
        {
            get
            {
                return _brand;
            }
            set
            {
                OnbrandChanging(value);
                ReportPropertyChanging("brand");
                _brand = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("brand");
                OnbrandChanged();
            }
        }
        private global::System.String _brand;
        partial void OnbrandChanging(global::System.String value);
        partial void OnbrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String image
        {
            get
            {
                return _image;
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.String _image;
        partial void OnimageChanging(global::System.String value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.String _price;
        partial void OnpriceChanging(global::System.String value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime poston
        {
            get
            {
                return _poston;
            }
            set
            {
                OnpostonChanging(value);
                ReportPropertyChanging("poston");
                _poston = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("poston");
                OnpostonChanged();
            }
        }
        private global::System.DateTime _poston;
        partial void OnpostonChanging(global::System.DateTime value);
        partial void OnpostonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String area
        {
            get
            {
                return _area;
            }
            set
            {
                OnareaChanging(value);
                ReportPropertyChanging("area");
                _area = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("area");
                OnareaChanged();
            }
        }
        private global::System.String _area;
        partial void OnareaChanging(global::System.String value);
        partial void OnareaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="city")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class city : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new city object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="cityname">Initial value of the cityname property.</param>
        public static city Createcity(global::System.Int32 id, global::System.String cityname)
        {
            city city = new city();
            city.id = id;
            city.cityname = cityname;
            return city;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cityname
        {
            get
            {
                return _cityname;
            }
            set
            {
                OncitynameChanging(value);
                ReportPropertyChanging("cityname");
                _cityname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cityname");
                OncitynameChanged();
            }
        }
        private global::System.String _cityname;
        partial void OncitynameChanging(global::System.String value);
        partial void OncitynameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbaseModel", "FK_area_city", "area")]
        public EntityCollection<area> areas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<area>("dbaseModel.FK_area_city", "area");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<area>("dbaseModel.FK_area_city", "area", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="contactinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class contactinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new contactinfo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="phoneno">Initial value of the phoneno property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="city">Initial value of the city property.</param>
        /// <param name="area">Initial value of the area property.</param>
        public static contactinfo Createcontactinfo(global::System.Int32 id, global::System.String name, global::System.String email, global::System.String phoneno, global::System.String password, global::System.String city, global::System.String area)
        {
            contactinfo contactinfo = new contactinfo();
            contactinfo.id = id;
            contactinfo.name = name;
            contactinfo.email = email;
            contactinfo.phoneno = phoneno;
            contactinfo.password = password;
            contactinfo.city = city;
            contactinfo.area = area;
            return contactinfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phoneno
        {
            get
            {
                return _phoneno;
            }
            set
            {
                OnphonenoChanging(value);
                ReportPropertyChanging("phoneno");
                _phoneno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phoneno");
                OnphonenoChanged();
            }
        }
        private global::System.String _phoneno;
        partial void OnphonenoChanging(global::System.String value);
        partial void OnphonenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String area
        {
            get
            {
                return _area;
            }
            set
            {
                OnareaChanging(value);
                ReportPropertyChanging("area");
                _area = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("area");
                OnareaChanged();
            }
        }
        private global::System.String _area;
        partial void OnareaChanging(global::System.String value);
        partial void OnareaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="furniture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class furniture : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new furniture object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="location">Initial value of the location property.</param>
        /// <param name="poston">Initial value of the poston property.</param>
        public static furniture Createfurniture(global::System.Int32 id, global::System.String title, global::System.String description, global::System.Double price, global::System.String status, global::System.String location, global::System.DateTime poston)
        {
            furniture furniture = new furniture();
            furniture.id = id;
            furniture.title = title;
            furniture.description = description;
            furniture.price = price;
            furniture.status = status;
            furniture.location = location;
            furniture.poston = poston;
            return furniture;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Double _price;
        partial void OnpriceChanging(global::System.Double value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String image
        {
            get
            {
                return _image;
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.String _image;
        partial void OnimageChanging(global::System.String value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime poston
        {
            get
            {
                return _poston;
            }
            set
            {
                OnpostonChanging(value);
                ReportPropertyChanging("poston");
                _poston = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("poston");
                OnpostonChanged();
            }
        }
        private global::System.DateTime _poston;
        partial void OnpostonChanging(global::System.DateTime value);
        partial void OnpostonChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="house")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class house : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new house object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="housesize">Initial value of the housesize property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="location">Initial value of the location property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="image">Initial value of the image property.</param>
        /// <param name="poston">Initial value of the poston property.</param>
        public static house Createhouse(global::System.Int32 id, global::System.String address, global::System.String housesize, global::System.String title, global::System.String description, global::System.Double price, global::System.String location, global::System.String status, global::System.String image, global::System.DateTime poston)
        {
            house house = new house();
            house.id = id;
            house.address = address;
            house.housesize = housesize;
            house.title = title;
            house.description = description;
            house.price = price;
            house.location = location;
            house.status = status;
            house.image = image;
            house.poston = poston;
            return house;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String housesize
        {
            get
            {
                return _housesize;
            }
            set
            {
                OnhousesizeChanging(value);
                ReportPropertyChanging("housesize");
                _housesize = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("housesize");
                OnhousesizeChanged();
            }
        }
        private global::System.String _housesize;
        partial void OnhousesizeChanging(global::System.String value);
        partial void OnhousesizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Double _price;
        partial void OnpriceChanging(global::System.Double value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String image
        {
            get
            {
                return _image;
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.String _image;
        partial void OnimageChanging(global::System.String value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime poston
        {
            get
            {
                return _poston;
            }
            set
            {
                OnpostonChanging(value);
                ReportPropertyChanging("poston");
                _poston = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("poston");
                OnpostonChanged();
            }
        }
        private global::System.DateTime _poston;
        partial void OnpostonChanging(global::System.DateTime value);
        partial void OnpostonChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="job")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class job : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new job object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="category">Initial value of the category property.</param>
        /// <param name="jobtype">Initial value of the jobtype property.</param>
        /// <param name="website">Initial value of the website property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="salary">Initial value of the salary property.</param>
        /// <param name="jobtitle">Initial value of the jobtitle property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="coname">Initial value of the coname property.</param>
        /// <param name="location">Initial value of the location property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="poston">Initial value of the poston property.</param>
        public static job Createjob(global::System.Int32 id, global::System.String category, global::System.String jobtype, global::System.String website, global::System.String phone, global::System.String salary, global::System.String jobtitle, global::System.String description, global::System.String coname, global::System.String location, global::System.String status, global::System.DateTime poston)
        {
            job job = new job();
            job.id = id;
            job.category = category;
            job.jobtype = jobtype;
            job.website = website;
            job.phone = phone;
            job.salary = salary;
            job.jobtitle = jobtitle;
            job.description = description;
            job.coname = coname;
            job.location = location;
            job.status = status;
            job.poston = poston;
            return job;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.String _category;
        partial void OncategoryChanging(global::System.String value);
        partial void OncategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String jobtype
        {
            get
            {
                return _jobtype;
            }
            set
            {
                OnjobtypeChanging(value);
                ReportPropertyChanging("jobtype");
                _jobtype = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("jobtype");
                OnjobtypeChanged();
            }
        }
        private global::System.String _jobtype;
        partial void OnjobtypeChanging(global::System.String value);
        partial void OnjobtypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String website
        {
            get
            {
                return _website;
            }
            set
            {
                OnwebsiteChanging(value);
                ReportPropertyChanging("website");
                _website = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("website");
                OnwebsiteChanged();
            }
        }
        private global::System.String _website;
        partial void OnwebsiteChanging(global::System.String value);
        partial void OnwebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String salary
        {
            get
            {
                return _salary;
            }
            set
            {
                OnsalaryChanging(value);
                ReportPropertyChanging("salary");
                _salary = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("salary");
                OnsalaryChanged();
            }
        }
        private global::System.String _salary;
        partial void OnsalaryChanging(global::System.String value);
        partial void OnsalaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String jobtitle
        {
            get
            {
                return _jobtitle;
            }
            set
            {
                OnjobtitleChanging(value);
                ReportPropertyChanging("jobtitle");
                _jobtitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("jobtitle");
                OnjobtitleChanged();
            }
        }
        private global::System.String _jobtitle;
        partial void OnjobtitleChanging(global::System.String value);
        partial void OnjobtitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String coname
        {
            get
            {
                return _coname;
            }
            set
            {
                OnconameChanging(value);
                ReportPropertyChanging("coname");
                _coname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("coname");
                OnconameChanged();
            }
        }
        private global::System.String _coname;
        partial void OnconameChanging(global::System.String value);
        partial void OnconameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime poston
        {
            get
            {
                return _poston;
            }
            set
            {
                OnpostonChanging(value);
                ReportPropertyChanging("poston");
                _poston = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("poston");
                OnpostonChanged();
            }
        }
        private global::System.DateTime _poston;
        partial void OnpostonChanging(global::System.DateTime value);
        partial void OnpostonChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="land")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class land : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new land object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="image">Initial value of the image property.</param>
        /// <param name="poston">Initial value of the poston property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="location">Initial value of the location property.</param>
        public static land Createland(global::System.Int32 id, global::System.String title, global::System.Byte[] image, global::System.DateTime poston, global::System.String status, global::System.String location)
        {
            land land = new land();
            land.id = id;
            land.title = title;
            land.image = image;
            land.poston = poston;
            land.status = status;
            land.location = location;
            return land;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] image
        {
            get
            {
                return StructuralObject.GetValidValue(_image);
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.Byte[] _image;
        partial void OnimageChanging(global::System.Byte[] value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime poston
        {
            get
            {
                return _poston;
            }
            set
            {
                OnpostonChanging(value);
                ReportPropertyChanging("poston");
                _poston = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("poston");
                OnpostonChanged();
            }
        }
        private global::System.DateTime _poston;
        partial void OnpostonChanging(global::System.DateTime value);
        partial void OnpostonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new menu object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="navurl">Initial value of the navurl property.</param>
        /// <param name="parentid">Initial value of the parentid property.</param>
        public static menu Createmenu(global::System.Int32 id, global::System.String name, global::System.String navurl, global::System.Int32 parentid)
        {
            menu menu = new menu();
            menu.id = id;
            menu.name = name;
            menu.navurl = navurl;
            menu.parentid = parentid;
            return menu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String navurl
        {
            get
            {
                return _navurl;
            }
            set
            {
                OnnavurlChanging(value);
                ReportPropertyChanging("navurl");
                _navurl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("navurl");
                OnnavurlChanged();
            }
        }
        private global::System.String _navurl;
        partial void OnnavurlChanging(global::System.String value);
        partial void OnnavurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parentid
        {
            get
            {
                return _parentid;
            }
            set
            {
                OnparentidChanging(value);
                ReportPropertyChanging("parentid");
                _parentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentid");
                OnparentidChanged();
            }
        }
        private global::System.Int32 _parentid;
        partial void OnparentidChanging(global::System.Int32 value);
        partial void OnparentidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbaseModel", "FK_menu_menu", "menu1")]
        public menu menu1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("dbaseModel.FK_menu_menu", "menu1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("dbaseModel.FK_menu_menu", "menu1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<menu> menu1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("dbaseModel.FK_menu_menu", "menu1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<menu>("dbaseModel.FK_menu_menu", "menu1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbaseModel", "FK_menu_menu", "menu")]
        public menu menu2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("dbaseModel.FK_menu_menu", "menu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("dbaseModel.FK_menu_menu", "menu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<menu> menu2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<menu>("dbaseModel.FK_menu_menu", "menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<menu>("dbaseModel.FK_menu_menu", "menu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbaseModel", Name="mobile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mobile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mobile object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="brandname">Initial value of the brandname property.</param>
        /// <param name="modelno">Initial value of the modelno property.</param>
        /// <param name="image">Initial value of the image property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="poston">Initial value of the poston property.</param>
        public static mobile Createmobile(global::System.Int32 id, global::System.String brandname, global::System.String modelno, global::System.String image, global::System.Double price, global::System.String poston)
        {
            mobile mobile = new mobile();
            mobile.id = id;
            mobile.brandname = brandname;
            mobile.modelno = modelno;
            mobile.image = image;
            mobile.price = price;
            mobile.poston = poston;
            return mobile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String brandname
        {
            get
            {
                return _brandname;
            }
            set
            {
                OnbrandnameChanging(value);
                ReportPropertyChanging("brandname");
                _brandname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("brandname");
                OnbrandnameChanged();
            }
        }
        private global::System.String _brandname;
        partial void OnbrandnameChanging(global::System.String value);
        partial void OnbrandnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String modelno
        {
            get
            {
                return _modelno;
            }
            set
            {
                OnmodelnoChanging(value);
                ReportPropertyChanging("modelno");
                _modelno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("modelno");
                OnmodelnoChanged();
            }
        }
        private global::System.String _modelno;
        partial void OnmodelnoChanging(global::System.String value);
        partial void OnmodelnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String image
        {
            get
            {
                return _image;
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.String _image;
        partial void OnimageChanging(global::System.String value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Double _price;
        partial void OnpriceChanging(global::System.Double value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String poston
        {
            get
            {
                return _poston;
            }
            set
            {
                OnpostonChanging(value);
                ReportPropertyChanging("poston");
                _poston = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("poston");
                OnpostonChanged();
            }
        }
        private global::System.String _poston;
        partial void OnpostonChanging(global::System.String value);
        partial void OnpostonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion

    
    }

    #endregion

    
}
